
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace ola.model
{

using System;
    using System.Collections.Generic;
    
public partial class LotteryOpenTime
{

    public System.Guid Id { get; set; }

    public int LotteryId { get; set; }

    public string PreQiHao { get; set; }

    public string QiHao { get; set; }

    public string NextQiHao { get; set; }

    public System.DateTime OpenTime { get; set; }

    public System.DateTime CreateTime { get; set; }

    public System.DateTime StartTime { get; set; }

    public System.DateTime EndTime { get; set; }

}

}
