

//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace ola.model
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class OlaEntities : DbContext
{
    public OlaEntities()
        : base("name=OlaEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<LotteryOpenTime> LotteryOpenTimes { get; set; }

    public virtual DbSet<Log> Logs { get; set; }

    public virtual DbSet<LotteryOpenHistory> LotteryOpenHistories { get; set; }

    public virtual DbSet<AuthCode> AuthCodes { get; set; }

    public virtual DbSet<Account> Accounts { get; set; }

    public virtual DbSet<WeiXinUser> WeiXinUsers { get; set; }

}

}

