
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace ola.model
{

using System;
    using System.Collections.Generic;
    
public partial class WeiXinUser
{

    public int Id { get; set; }

    public string openid { get; set; }

    public string nickname { get; set; }

    public Nullable<int> sex { get; set; }

    public string province { get; set; }

    public string city { get; set; }

    public string country { get; set; }

    public string headimgurl { get; set; }

    public string unionid { get; set; }

    public string phone { get; set; }

    public Nullable<System.DateTime> CreateTime { get; set; }

    public string AuthCode { get; set; }

    public Nullable<int> state { get; set; }

}

}
